import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/custom/Navbar";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
          <body className={`${inter.className} flex flex-col min-h-screen`}>
            <Navbar />
            <main className="flex-1 flex flex-col">
              {children}
            </main>
          </body>
      </html>
    </ClerkProvider>
  );
}
